#!/bin/bash
set -eou pipefail

docker images ${1}
docker save ${1} | pv | (eval $(minikube docker-env) && docker load)

# If the older images with the same name become dangling, remove those dangling images from minikube
eval $(minikube docker-env)
dangling_images=`docker images -f "dangling=true" -q`

if [[ ! -z $dangling_images ]]; then
    echo "Removing dangling images"
    docker rmi $dangling_images
fi
